Repository ToriArtis/2NY-Frontend, pull requests merged in 2024-07, with the labels that each got.

#4 ✨ Feat: localstorage add
  src/cart/viewModels/UserViewModel.js
  src/config/app-config.js
  src/items/viewModels/UserViewModel.js
  src/orders/viewModels/UserViewModel.js
  src/review/viewModels/UserViewModel.js
  src/users/api/user.js
  src/users/api/userApi.js
  src/users/components/common/Button.js
  src/users/components/common/TextField.js
  src/users/hooks/useForm.js
  src/users/hooks/useUser.js
  src/users/models/User.js
  src/users/models/UserModel.js
  src/users/viewModels/useLoginViewModel.js
  src/users/viewModels/useSignUpViewModel.js
  src/users/views/LoginView.js
  src/users/views/SignUpView.js
  src/users/views/User.JS
Labels: ✨Feat, 👻Etc, 🥕 채현영🥕

#7 💄Style : Footer UI 추가
  package-lock.json
  package.json
  public/assets/figma.png
  public/assets/jira.png
  public/logo192.png
  public/logo512.png
  src/App.js
  src/AppRouter.js
  src/component/Footer.js
  src/component/Header.js
  src/index.js
  src/routes.js
  src/users/api/userApi.js
  src/users/hooks/useForm.js
  src/users/models/User.js
  src/users/viewModels/useLoginViewModel.js
  src/users/viewModels/useSignUpViewModel.js
  src/users/views/LoginView.js
  src/users/views/SignUpView.js
Labels: ✨Feat, 👻Etc, 🥕 채현영🥕, 💄Design

#12 ✨Feat: sign up 기능 추가
  src/component/BlueButton.js
  src/component/WhiteButton.js
  src/component/css/rainbow.css
  src/users/api/userApi.js
  src/users/components/css/users.css
  src/users/models/User.js
  src/users/viewModels/useSignUpViewModel.js
  src/users/views/LoginView.js
  src/users/views/SignUpView.js
Labels: ✨Feat, 👻Etc, 🥕 채현영🥕, 💄Design

#14 💄 Style : Navbar design
  public/assets/Logout.png
  public/assets/Search.png
  public/assets/Shopping bag.png
  public/assets/User.png
  public/assets/logo.png
  src/App.js
  src/component/Header.js
  src/component/css/header.css
  src/config/app-config.js
  src/users/api/userApi.js
Labels: ♻️Refactor, 🥕 채현영🥕, 💄Design

#15 💄 Style: auth side navbar 와이어프레임
  src/AppRouter.js
  src/users/components/common/UserRoleInfo.js
  src/users/views/InfoView.js
  src/users/views/UserInfoView.js
Labels: 🥕 채현영🥕, 💄Style

#16 ✨Feat: user information add
  src/AppRouter.js
  src/component/pages/InfoPage.js
  src/users/api/userApi.js
  src/users/viewModels/userInfoViewModel.js
  src/users/viewModels/userLoginViewModel.js
  src/users/views/InfoView.js
  src/users/views/UserInfoView.js
Labels: ✨Feat, 🥕 채현영🥕

#19 ✨ Feat: Cart + Order list wireframe
  .gitignore
  package-lock.json
  src/AppRouter.js
  src/cart/api/cartApi.js
  src/cart/models/UserModel.js
  src/cart/viewModels/CartListViewModel.js
  src/cart/viewModels/UserViewModel.js
  src/cart/views/CartList.js
  src/cart/views/User.JS
  src/component/css/CartsListPage.css
  src/component/css/OrdersListPage.css
  src/component/pages/CartsListPage.js
  src/component/pages/InfoPage.js
  src/component/pages/OrdersListPage.js
  src/orders/api/ordersApi.js
  src/orders/api/user.js
  src/orders/models/Orders.js
  src/orders/models/UserModel.js
  src/orders/viewModels/OrdersListViewModel.js
  src/orders/viewModels/UserViewModel.js
  src/orders/views/OrdersList.JS
  src/orders/views/User.JS
  src/users/components/common/UserRoleInfo.js
Labels: ✨Feat, 👻Etc, 🦦 김신이🦦

#18 ✨Feat: Item detail info
  src/App.js
  src/AppRouter.js
  src/items/views/ItemListView.js
Labels: ✨Feat

#20 ✨Feat: info page 기능 추가
  src/App.js
  src/AppRouter.js
  src/component/pages/InfoPage.js
  src/users/api/userApi.js
  src/users/api/userLoginApi.js
  src/users/components/common/UserRoleInfo.js
  src/users/viewModels/useInfoViewModel.js
  src/users/viewModels/useSignUpViewModel.js
  src/users/viewModels/userLoginViewModel.js
  src/users/views/LoginView.js
  src/users/views/UserInfoView.js
Labels: 🐛bug, ✨Feat, 👻Etc, 🥕 채현영🥕, 💄Style

#22 ✨Feat: 수정, 탈퇴 기능 추가
  src/AppRouter.js
  src/component/pages/InfoPage.js
  src/users/api/userApi.js
  src/users/components/common/PasswordVaild.js
  src/users/components/common/UserInfo.js
  src/users/components/common/UserRoleInfo.js
  src/users/viewModels/useModifyViewModel.js
  src/users/views/DeleteView.js
  src/users/views/InfoView.js
  src/users/views/ModifyView.js
  src/users/views/UserInfoView.js
Labels: ✨Feat, 🥕 채현영🥕

#23 ✨ Feat:modify
  src/component/pages/InfoPage.js
  src/users/api/userApi.js
  src/users/components/common/UserInfo.js
  src/users/components/common/UserRoleInfo.js
  src/users/hooks/useForm.js
  src/users/viewModels/useModifyViewModel.js
  src/users/views/ModifyView.js
Labels: ✨Feat, 🥕 채현영🥕

#24 ✨ Feat: Main page end
  public/assets/1.png
  public/assets/2.png
  public/assets/bannder.png
  public/assets/blur.png
  src/AppRouter.js
  src/items/components/css/MainPage.css
  src/items/views/ItemListView.js
Labels: ✨Feat, 🍸조민준🍸, 💄Style

#25 ✨Feat: Review Delete Add
  src/component/pages/UserReviewListPage.js
  src/review/api/reviewApi.js
  src/review/viewModels/UserListViewModel.js
Labels: ✨Feat, 👻Etc, 🔮 이소현🔮

#26 ✨Feat: Cart CRUD
  src/cart/api/cartApi.js
  src/cart/components/AddToCartButton.js
  src/cart/components/Auth.js
  src/cart/components/CartsList.js
  src/cart/hooks/useCart.js
  src/cart/hooks/useCartAction.js
  src/cart/hooks/useUser.js
  src/cart/models/Carts.js
  src/cart/models/UserModel.js
  src/cart/viewModels/CartListViewModel.js
  src/cart/viewModels/useCartListViewModel.js
  src/cart/views/CartList.js
  src/component/css/CartsListPage.css
  src/component/pages/CartsListPage.js
Labels: ✨Feat, 👻Etc, 🦦 김신이🦦, 💄Style

#28 ✨Feat: Cart In ItemImage
  package-lock.json
  src/cart/api/cartApi.js
  src/cart/components/AddToCartButton.js
  src/cart/components/CartItem.js
  src/cart/components/CartsList.js
  src/cart/hooks/useCart.js
  src/cart/models/Carts.js
  src/cart/viewModels/useCartListViewModel.js
  src/cart/views/CartList.js
  src/cart/views/CartListPage.js
Labels: 🧵Chore, ✨Feat, 👻Etc, 🦦 김신이🦦

#29 # ✨Feat: Review create,modify Add
  package-lock.json
  package.json
  src/AppRouter.js
  src/component/pages/OrdersListPage.js
  src/component/pages/UserReviewListPage.js
  src/review/api/reviewApi.js
  src/review/components/Auth.js
  src/review/components/StarRating.js
  src/review/hooks/useForm.js
  src/review/hooks/useUser.js
  src/review/viewModels/CreateReviewViewModel.js
  src/review/viewModels/ModifyReviewViewModel.js
  src/review/views/CreateReviewView.js
  src/review/views/ModifyReviewView.js
Labels: ✨Feat, 👻Etc, 🔮 이소현🔮

#30 🐛Fix: Cart RUD Fix
  src/cart/api/cartApi.js
  src/cart/components/AddToCartButton.js
  src/cart/components/CartItem.js
  src/cart/components/CartsList.js
  src/cart/hooks/useCart.js
  src/cart/models/Carts.js
  src/cart/viewModels/useCartListViewModel.js
  src/cart/views/CartListPage.js
  src/component/css/CartsListPage.css
Labels: 🐛bug, 🦦 김신이🦦, 💄Style

#31 ✨Feat: Order CR + Cart C
  src/AppRouter.js
  src/cart/api/cartApi.js
  src/cart/components/CartItem.js
  src/cart/hooks/useCart.js
  src/component/css/OrdersListPage.css
  src/component/pages/OrdersListPage.js
  src/items/views/ItemDetailView.js
  src/orders/api/ordersApi.js
  src/orders/components/Auth.js
  src/orders/components/OrderDetail.js
  src/orders/components/OrderItem.js
  src/orders/components/OrdersList.js
  src/orders/components/css/OrderDetailPage.css
  src/orders/hooks/useOrder.js
  src/orders/hooks/useOrders.js
  src/orders/hooks/useUser.js
  src/orders/models/Orders.js
  src/orders/viewModels/OrderDetailViewModel.js
  src/orders/viewModels/OrdersListViewModel.js
  src/orders/views/OrderDetailPage.js
  src/orders/views/OrdersList.JS
  src/orders/views/OrdersListPage.JS
Labels: 🧵Chore, ✨Feat, 👻Etc, 🦦 김신이🦦, 💄Style

#32 ✨Feat: Item CRUD
  src/AppRouter.js
  src/items/api/itemApiSimple.js
  src/items/components/css/CreateItem.css
  src/items/components/css/EditItem.css
  src/items/components/css/ItemDetail.css
  src/items/components/css/MainPage.css
  src/items/viewModels/useItemCreateViewModel.js
  src/items/viewModels/useItemEditViewModel.js
  src/items/views/ItemCreateView.js
  src/items/views/ItemDetailView.js
  src/items/views/ItemEditView.js
  src/items/views/ItemListView.js
Labels: 🐛bug, ✨Feat, 🍸조민준🍸, 💄Style

#33 🐛Fix: Review CRUD Fix
  src/component/css/UserReviewListPage.css
  src/component/pages/UserReviewListPage.js
  src/review/components/StarRating.js
  src/review/models/Review.js
  src/review/viewModels/CreateReviewViewModel.js
  src/review/viewModels/ModifyReviewViewModel.js
  src/review/views/CreateReviewView.js
  src/review/views/ModifyReviewView.js
Labels: 🐛bug, 🔮 이소현🔮

#34 ✨Feat: admin user 화면 넣음
  package-lock.json
  package.json
  src/AppRouter.js
  src/component/Header.js
  src/component/pages/InfoPage.js
  src/users/components/common/AdminRoleInfo.js
Labels: ✨Feat, 🥕 채현영🥕

#35 ✨Feat: Order Delete
  src/cart/components/CartsList.js
  src/component/css/CartsListPage.css
  src/component/pages/CartsListPage.js
  src/component/pages/OrdersListPage.js
  src/items/views/ItemDetailView.js
  src/orders/api/ordersApi.js
  src/orders/components/OrderDetail.js
  src/orders/components/OrderItem.js
  src/orders/components/OrdersList.js
  src/orders/components/css/OrderDetailPage.css
  src/orders/components/css/OrdersListPage.css
  src/orders/hooks/useOrder.js
  src/orders/viewModels/OrderDetailViewModel.js
  src/orders/views/OrderDetailPage.js
  src/orders/views/OrdersListPage.JS
  src/users/components/common/AdminRoleInfo.js
  src/users/components/common/UserRoleInfo.js
Labels: 🧵Chore, ✨Feat, 👻Etc, 🦦 김신이🦦, 💄Style

#36 ✨Feat: Purchase + Admin Order
  src/AppRouter.js
  src/cart/components/CartsList.js
  src/cart/components/css/PurchasePage.css
  src/cart/views/PurchasePage.js
  src/items/views/ItemDetailView.js
  src/orders/api/ordersApi.js
  src/orders/components/OrderItem.js
  src/orders/components/OrdersList.js
  src/orders/hooks/useOrders.js
  src/orders/viewModels/OrdersListViewModel.js
  src/orders/views/OrdersListPage.JS
  src/users/api/userApi.js
  src/users/components/common/AdminRoleInfo.js
Labels: 🧵Chore, ✨Feat, 🦦 김신이🦦, 💄Style

#37 ✨Feat: Item CRUD wireframe finished
  src/items/api/itemApiSimple.js
  src/items/viewModels/useItemCreateViewModel.js
  src/items/viewModels/useItemEditViewModel.js
  src/items/views/ItemDetailView.js
  src/items/views/ItemEditView.js
Labels: 🐛bug, ✨Feat, 🍸조민준🍸

#38 💄Style: HEADER align center
  src/AppRouter.js
  src/component/Header.js
  src/component/css/header.css
  src/items/components/css/AllList.css
  src/items/views/ItemAllListView.js
Labels: ✨Feat, 💄Style

#39 ✨ Feat: admin user mypage add
  src/component/pages/InfoPage.js
  src/users/components/common/AdminRoleInfo.js
  src/users/components/common/UserRoleInfo.js
  src/users/views/ModifyView.js
Labels: 🐛bug, ✨Feat, 🥕 채현영🥕

#40 Feat: 챗봇 -> chat gpt
  src/AppRouter.js
  src/chat/ChatViewModel.js
  src/chat/ChatbotView.css
  src/chat/ChatbotView.js
  src/chat/chatModel.js
  src/items/views/ItemListView.js
  src/users/api/userApi.js
Labels: ♻️Refactor, ✨Feat, 🥕 채현영🥕, 💄Style

#42 🐛Fix: apiSimple assemble
  src/items/api/itemApi.js
  src/items/hooks/useItemViewModel.js
  src/items/viewModels/useItemEditViewModel.js
  src/items/views/ItemDetailView.js
  src/review/components/StarRating.js
  src/users/components/common/AdminRoleInfo.js
Labels: 🐛bug, 📝Docs, 🍸조민준🍸, 🔮 이소현🔮

#43 🐛Fix: Order FileName Fix + ADMIN Cart,Order + PurchasePage
  package-lock.json
  package.json
  src/cart/api/cartApi.js
  src/cart/components/CartsList.js
  src/cart/components/css/PurchasePage.css
  src/cart/hooks/useCart.js
  src/cart/views/PurchasePage.js
  src/component/css/CartsListPage.css
  src/items/views/ItemDetailView.js
  src/orders/api/ordersApi.js
  src/orders/components/OrderDetail.js
  src/orders/components/OrderItem.js
  src/orders/components/OrdersList.js
  src/orders/components/css/OrdersListPage.css
  src/orders/hooks/useOrder.js
  src/orders/viewModels/OrdersListViewModel.js
  src/orders/views/OrderDetailPage.js
  src/orders/views/OrdersListPage.JS
  src/users/components/common/AdminRoleInfo.js
  src/users/components/common/UserRoleInfo.js
Labels: 🐛bug, ✨Feat, 👻Etc, 🦦 김신이🦦, 💄Style

#44 ♻️Refactor: OrdersListPage => OrderListPage
  src/orders/views/OrderListPage.js
  src/users/components/common/AdminRoleInfo.js
  src/users/components/common/UserRoleInfo.js
Labels: ♻️Refactor, 🦦 김신이🦦

#45 💄Style: Item page styling 🐛Fix: All list Pagination
  src/AppRouter.js
  src/component/Header.js
  src/items/api/itemApi.js
  src/items/components/ItemCard.js
  src/items/components/css/AllList.css
  src/items/components/css/ItemDetail.css
  src/items/components/css/MainPage.css
  src/items/hooks/useItemViewModel.js
  src/items/views/ItemAllListView.js
  src/items/views/ItemCreateView.js
  src/items/views/ItemDetailView.js
  src/items/views/ItemListView.js
  src/users/components/common/AdminRoleInfo.js
Labels: 🐛bug, 🍸조민준🍸, 💄Style

#46 ✨Feat: ImageView
  src/config/app-config.js
  src/items/components/ItemCard.js
  src/items/viewModels/useItemCreateViewModel.js
  src/items/views/ItemDetailView.js
Labels: ✨Feat, 🔮 이소현🔮

#47 🐛fix: Item edit path fix, item delete button feat
  src/items/api/itemApi.js
  src/items/components/css/AllList.css
  src/items/components/css/EditItem.css
  src/items/components/css/ItemDetail.css
  src/items/hooks/useItemViewModel.js
  src/items/views/ItemAllListView.js
  src/items/views/ItemDetailView.js
  src/items/views/ItemEditView.js
Labels: 🐛bug, ✨Feat, 🍸조민준🍸, 💄Style

#48 🐛Fix: ItemModify Fix
  src/items/api/itemApi.js
Labels: 🐛bug, 🔮 이소현🔮

#51 🐛Fix: 잡다한 수정
  src/component/Header.js
  src/component/pages/InfoPage.js
  src/users/api/userApi.js
  src/users/api/userLoginApi.js
  src/users/components/common/PasswordVaild.js
  src/users/views/InfoView.js
  src/users/views/PasswordFindView.js
Labels: 🐛bug, 🥕 채현영🥕

#53 🧵 Error Modify
  .vscode/extensions.json
  .vscode/settings.json
  src/items/views/ItemListView.js
  src/orders/components/OrderDetail.js
  src/review/viewModels/CreateReviewViewModel.js
Labels: 🧵Chore, 🔮 이소현🔮

#54 ✨ Feat: password find
  src/AppRouter.js
  src/users/api/userApi.js
  src/users/models/User.js
  src/users/viewModels/usePasswordFindViewModel.js
  src/users/views/LoginView.js
  src/users/views/PasswordFindView.js
  src/users/views/SignUpView.js
Labels: ✨Feat, 🥕 채현영🥕, 💄Style

#55 🐛Fix: Admin Order UserInfo Fix + CSS Fix
  package-lock.json
  src/cart/views/PurchasePage.js
  src/component/Header.js
  src/orders/components/AdminOrderItem.js
  src/orders/components/AdminOrdersList.js
  src/orders/components/OrderDetail.js
  src/orders/components/css/AdminOrdersListPage.css
  src/orders/models/Orders.js
  src/users/components/common/AdminRoleInfo.js
Labels: 🐛bug, 👻Etc, 🦦 김신이🦦, 💄Style

#56 ✨ Feat: 이메일 찾기
  src/AppRouter.js
  src/users/api/userApi.js
  src/users/viewModels/useEmailFindViewModel.js
  src/users/views/EmailFind.js
  src/users/views/LoginView.js
Labels: ✨Feat, 🥕 채현영🥕

#57 🐛Fix : Item sort bug fix, Header category sort fix
  src/component/Header.js
  src/items/models/UserItem.js
  src/items/views/ItemAllListView.js
Labels: 🐛bug, 🍸조민준🍸

#58 ✨Feat Feat ItemDetail page StarRating
  src/items/views/ItemDetailView.js
Labels: 🐛bug, ✨Feat, 🍸조민준🍸, 💄Style

#59 💄Style: Admin + User Info Page Design ing...
  src/cart/components/css/PurchasePage.css
  src/component/css/header.css
  src/orders/components/css/AdminOrdersListPage.css
  src/orders/views/AdminOrdersListPage.js
  src/users/components/common/AdminRoleInfo.js
  src/users/components/common/UserRoleInfo.js
Labels: 🦦 김신이🦦, 💄Style

#61 ✨Feat Item detail page carousel add
  package-lock.json
  package.json
  src/items/components/css/ItemDetail.css
  src/items/views/ItemCreateView.js
  src/items/views/ItemDetailView.js
Labels: ✨Feat, 🍸조민준🍸, 💄Style

#64 🐛Fix: Order Detail + MyPage, Order CSS
  src/component/Header.js
  src/orders/components/OrderDetail.js
  src/orders/components/OrderItem.js
  src/orders/components/css/AdminOrdersListPage.css
  src/orders/components/css/OrdersListPage.css
  src/orders/hooks/useOrder.js
  src/orders/models/Orders.js
  src/users/components/common/PasswordVaild.js
Labels: 🐛bug, 🦦 김신이🦦, 💄Style

#65 ✨Feat: Search Again
  src/component/Header.js
  src/items/api/itemApi.js
  src/items/hooks/useItemViewModel.js
  src/items/views/ItemAllListView.js
Labels: ✨Feat, 🔮 이소현🔮

#67 🐛Fix: Item price 0$ fix
  src/items/api/itemApi.js
  src/items/viewModels/useItemCreateViewModel.js
  src/items/views/ItemEditView.js
  src/items/views/MypageItemCreateView.js
  src/users/components/common/AdminRoleInfo.js
Labels: 🐛bug, 🍸조민준🍸

#68 ✨ Feat: ItemDetailView feat content,popular items,💄Style: style content,popular items
  src/items/components/css/ItemDetail.css
  src/items/hooks/useItemViewModel.js
  src/items/viewModels/ItemViewModel.js
  src/items/views/ItemDetailView.js
Labels: ✨Feat, 🍸조민준🍸, 💄Style

#69 ✨Feat: DiscountPrice sort
  src/items/hooks/useItemViewModel.js
  src/items/views/ItemAllListView.js
Labels: 🐛bug, ✨Feat, 🍸조민준🍸

#70 🐛Fix: AdmminRoleInfo fix + CSS
  src/component/pages/InfoPage.js
  src/orders/components/css/AdminOrdersListPage.css
  src/users/components/common/UserRoleInfo.js
  src/users/views/ModifyView.js
Labels: 🐛bug, 🥕 채현영🥕, 🦦 김신이🦦, 💄Style

#71 🐛Fix: Price High,low sort bug fix
  src/items/hooks/useItemViewModel.js
  src/items/views/ItemAllListView.js
Labels: 🐛bug, 🍸조민준🍸

#72 🐛Fix Item search fix
  src/items/api/itemApi.js
  src/items/hooks/useItemViewModel.js
  src/items/views/ItemAllListView.js
Labels: 🐛bug, ✨Feat, 🍸조민준🍸, 🔮 이소현🔮

#74 ✨ Feat: search address
  .gitignore
  src/AppRouter.js
  src/users/components/AddressSearch.js
Labels: ✨Feat, 🥕 채현영🥕

#77 🧵Chore: Cart Hook Delete + Orders Code Clean Up
  package-lock.json
  src/cart/hooks/useCartAction.js
  src/orders/components/OrderDetail.js
  src/orders/viewModels/OrdersListViewModel.js
  src/orders/views/OrderListPage.js
Labels: 🧵Chore, 🦦 김신이🦦

#79 🐛Fix: Review CreateId&Url Fix
  src/orders/components/OrderDetail.js
  src/orders/views/OrderDetailPage.js
  src/review/viewModels/CreateReviewViewModel.js
  src/review/views/CreateReviewView.js
Labels: 🐛bug, 🔮 이소현🔮

#80 ✨Feat: Sosial login finish - Google,Naver,Kakao
  .gitignore
  src/AppRouter.js
  src/items/hooks/useItemViewModel.js
  src/users/components/OAuthRedirectHandler.js
  src/users/views/LoginView.js
Labels: ✨Feat

#82 🐛Fix: Review Create,Modify Fix
  src/component/pages/UserReviewListPage.js
  src/orders/components/OrderDetail.js
  src/review/viewModels/CreateReviewViewModel.js
  src/review/viewModels/ModifyReviewViewModel.js
  src/review/views/CreateReviewView.js
  src/review/views/ModifyReviewView.js
Labels: 🐛bug, 🔮 이소현🔮

#83 🐛Fix: Env app key root fix
  src/items/components/css/ItemDetail.css
  src/users/views/LoginView.js
Labels: 🐛bug, 🍸조민준🍸

#86 ✨Feat: KakaoPay Api
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/cart/components/CartItem.js
  src/cart/views/PurchasePage.js
  src/orders/components/OrderDetail.js
Labels: ✨Feat, 👻Etc, 👗Style, 🦦 김신이🦦

#88 🐛Fix: Social Login Mypage Bug fix
  src/config/app-config.js
  src/users/components/OAuthRedirectHandler.js
Labels: 🐛bug, 🍸조민준🍸

#89 ✨Feat: 우편번호 찾기api 연결
  package-lock.json
  package.json
  src/AppRouter.js
  src/users/api/userApi.js
  src/users/components/AddressSearch.js
  src/users/components/css/users.css
  src/users/viewModels/useModifyViewModel.js
  src/users/viewModels/useSignUpViewModel.js
  src/users/views/DeleteView.js
  src/users/views/ModifyView.js
  src/users/views/SignUpView.js
Labels: 🐛bug, ✨Feat, 🥕 채현영🥕, 💄Style

#91 💄Style: MyPage + Review + Header CSS
  src/component/Header.js
  src/component/css/ModifyView.css
  src/component/css/UserReviewListPage.css
  src/component/css/header.css
  src/orders/components/css/AdminOrdersListPage.css
  src/orders/components/css/OrderDetailPage.css
  src/review/views/ModifyReviewView.js
  src/users/components/common/UserRoleInfo.js
Labels: 🦦 김신이🦦, 💄Style

#92 🐛Fix: Category + Filter Fix
  src/items/api/itemApi.js
  src/items/hooks/useItemViewModel.js
  src/items/views/ItemAllListView.js
Labels: 🐛bug, 🔮 이소현🔮

#93 💄Style: InfoModify + Cart CSS
  public/assets/kakaopay.png
  src/cart/components/CartsList.js
  src/cart/views/PurchasePage.js
  src/component/css/CartsListPage.css
  src/component/css/ModifyView.css
  src/component/css/header.css
  src/orders/components/css/AdminOrdersListPage.css
  src/orders/components/css/OrderDetailPage.css
  src/users/views/ModifyView.js
Labels: 🦦 김신이🦦, 💄Style

#94 ✨Feat: MarkDown Add
  package-lock.json
  package.json
  src/items/hooks/useItemViewModel.js
  src/items/viewModels/useItemCreateViewModel.js
  src/items/views/ItemCreateView.js
  src/items/views/ItemDetailView.js
Labels: ✨Feat, 🔮 이소현🔮

#95 🐛Fix: Item edit bug fix
  src/items/api/itemApi.js
  src/items/viewModels/useItemEditViewModel.js
  src/items/views/ItemEditView.js
Labels: 🐛bug, ✨Feat, 🍸조민준🍸

#96 💄Style: Review Design&Paginaion
  src/component/css/UserReviewListPage.css
  src/component/pages/UserReviewListPage.js
  src/items/api/itemApi.js
  src/items/components/css/ItemDetail.css
  src/items/hooks/useItemViewModel.js
  src/items/views/ItemDetailView.js
  src/review/api/reviewApi.js
  src/review/components/Pagination.js
  src/review/viewModels/CreateReviewViewModel.js
  src/review/viewModels/ModifyReviewViewModel.js
  src/review/viewModels/UserListViewModel.js
  src/review/views/CreateReviewView.js
  src/review/views/ModifyReviewView.js
  src/review/views/UserListView.JS
Labels: 🔮 이소현🔮, 💄Style

#97 💄Style: Cart + Order + Info + Purchase CSS
  package-lock.json
  package.json
  src/cart/api/cartApi.js
  src/cart/components/CartItem.js
  src/cart/components/CartsList.js
  src/cart/components/css/PurchasePage.css
  src/cart/hooks/useCart.js
  src/cart/views/CartListPage.js
  src/cart/views/PurchasePage.js
  src/component/Header.js
  src/component/css/CartsListPage.css
  src/component/css/ModifyView.css
  src/component/css/header.css
  src/component/pages/InfoPage.js
  src/orders/api/ordersApi.js
  src/orders/components/AdminOrderItem.js
  src/orders/components/AdminOrdersList.js
  src/orders/components/OrderItem.js
  src/orders/components/OrdersList.js
  src/orders/components/css/AdminOrdersListPage.css
  src/orders/components/css/OrdersListPage.css
  src/orders/models/Orders.js
  src/orders/views/OrderDetailPage.js
  src/orders/views/OrderListPage.js
  src/users/views/ModifyView.js
Labels: ✨Feat, 👗Style, 🦦 김신이🦦, 💄Style

#98 🐛Fix: Thumbnail image edit fix
  src/items/api/itemApi.js
  src/items/viewModels/useItemEditViewModel.js
  src/items/views/ItemEditView.js
Labels: 🐛bug, 🍸조민준🍸

#100 💄Style: Header style fix, category delete oldest
  src/component/Header.js
  src/component/css/header.css
  src/items/components/css/AllList.css
  src/items/views/ItemAllListView.js
Labels: 🍸조민준🍸, 💄Style

#101 🐛 Fix : oauth의 경우 password 검증 페이지를 따로 넣지 않음!
  src/component/BlueButton.js
  src/users/components/common/UserRoleInfo.js
  src/users/views/ModifyView.js
Labels: 🐛bug, 💄Style

#102 ✨Feat: Error Page Setting
  package-lock.json
  src/AppRouter.js
  src/component/css/ErrorPage.css
  src/error/api/errorApi.js
  src/error/components/ErrorBoundary.js
  src/error/hooks/useError.js
  src/error/models/Error.js
  src/error/viewModels/useErrorViewModel.js
  src/error/views/ErrorPage.js
  src/error/views/TestErrorPage.js
Labels: ✨Feat, 🦦 김신이🦦, 💄Style

#103 ✨ Feat : Loading Page
  src/users/components/OAuthRedirectHandler.js
  src/users/views/OauthLoadingPage.js
Labels: ✨Feat

#105 🧵Chore: Log delete
  src/cart/hooks/useCart.js
  src/cart/views/PurchasePage.js
  src/chat/ChatViewModel.js
  src/items/api/itemApi.js
  src/items/api/itemApiSimple.js
  src/items/hooks/useItemViewModel.js
  src/items/viewModels/ItemViewModel.js
  src/items/viewModels/useItemEditViewModel.js
  src/items/views/ItemAllListView.js
  src/items/views/ItemDetailView.js
  src/orders/api/ordersApi.js
  src/orders/components/AdminOrderItem.js
  src/orders/hooks/useOrder.js
  src/review/api/reviewApi.js
  src/review/viewModels/UserListViewModel.js
  src/review/views/CreateReviewView.js
  src/users/api/userApi.js
  src/users/api/userLoginApi.js
  src/users/components/OAuthRedirectHandler.js
  src/users/components/common/PasswordVaild.js
  src/users/viewModels/useEmailFindViewModel.js
  src/users/viewModels/useInfoViewModel.js
  src/users/viewModels/useLoginViewModel.js
  src/users/viewModels/usePasswordFindViewModel.js
  src/users/viewModels/useSignUpViewModel.js
  src/users/views/DeleteView.js
Labels: 🧵Chore, 🍸조민준🍸, 🔮 이소현🔮, 🥕 채현영🥕, 🦦 김신이🦦

#107 🐛 Item category fix, quill editor fix
  src/cart/components/CartItem.js
  src/cart/views/PurchasePage.js
  src/component/Footer.js
  src/items/views/ItemCreateView.js
  src/items/views/ItemDetailView.js
  src/items/views/ItemEditView.js
Labels: 🐛bug, 🍸조민준🍸

#108 🧵Chore: Cart + Purchase
  package-lock.json
  package.json
  src/cart/components/CartItem.js
  src/cart/views/PurchasePage.js
Labels: 🧵Chore, 🦦 김신이🦦
