Repository ToriArtis/2NY-Frontend, pull requests merged in 2024-09, with the labels that each got.

#118 💄 Style : Item create view, mainpage mobile view
  src/items/components/css/CreateItem.css
  src/items/components/css/MainPage.css
  src/items/views/ItemAllListView.js
  src/items/views/ItemCreateView.js
  src/items/views/ItemListView.js
Labels: 🍸조민준🍸, 💄Style

#119 🐛 Fix: Oauth fix
  src/users/views/LoginView.js
Labels: 🐛bug, 🍸조민준🍸

#120 🐛 Fix: Oauth fix
  .env
  src/Config.js
Labels: 🐛bug, 🍸조민준🍸

#121 👗Style: css fix
  src/component/Footer.js
  src/component/Header.js
  src/component/css/header.css
  src/index.js
  src/users/components/common/AdminRoleInfo.js
  src/users/components/common/PasswordVaild.js
  src/users/components/common/UserRoleInfo.js
  src/users/components/css/AdminRoleInfo.css
  src/users/components/css/UserRoleInfo.css
Labels: 👗Style, 🥕 채현영🥕, 💄Style

#122 💄 Style : Fix mainpage carosel, itemdetail
  src/items/components/css/ItemDetail.css
  src/items/components/css/MainPage.css
  src/items/views/ItemListView.js
Labels: 🍸조민준🍸, 💄Style

#123 💄 Style : userRoleInfo css fix
  src/users/components/css/UserRoleInfo.css
Labels: 🍸조민준🍸, 💄Style

#124 💄 Style : Header & mobile layout fix
  src/component/Header.js
  src/component/css/header.css
  src/items/components/css/AllList.css
  src/items/components/css/MainPage.css
  src/items/views/ItemListView.js
Labels: 🍸조민준🍸, 💄Style

#125 💄 Style : Fix Header
  src/component/css/header.css
Labels: 🍸조민준🍸, 💄Style

#126 ✨ Feat : Visitor statistics
  package-lock.json
  package.json
  src/component/Dashboard.js
  src/component/pages/ChartThree.js
  src/component/pages/Visitor.js
Labels: ✨Feat, 🔮 이소현🔮

#127 💄 Style : Visitor css
  src/component/pages/Visitor.js
Labels: 🔮 이소현🔮, 💄Style

#129 💄 Style : Dashboard Css End
  src/component/Dashboard.js
  src/component/pages/CardFour.js
  src/component/pages/CardOne.js
  src/component/pages/CardThree.js
  src/component/pages/CardTwo.js
  src/component/pages/ChartTwo.js
  src/component/pages/ChatCard.js
  src/component/pages/SalesChart.js
  src/component/pages/TopCategoryChart.js
  src/component/pages/TopSalesChart.js
Labels: 🔮 이소현🔮, 💄Style

#130 💄 Style : Header css
  src/component/Header.js
  src/component/css/header.css
Labels: 🔮 이소현🔮, 💄Style

#132 ✨ Feat : S3 image upload
  src/config/app-config.js
  src/items/api/itemApi.js
  src/items/components/ItemCard.js
  src/items/views/ItemAllListView.js
  src/items/views/ItemDetailView.js
  src/items/views/ItemListView.js
Labels: 🐛bug, ✨Feat, 🍸조민준🍸

#134 🐛 Fix : header hide
  .gitignore
  src/component/Header.js
Labels: 🐛bug, 🔮 이소현🔮

#136 🐛 Fix : deploy visitor fix
  src/config/app-config.js
Labels: 🐛bug, 🍸조민준🍸

#137 ✨ Feat : localStorage Encrypt
  package-lock.json
  package.json
  src/cart/api/cartApi.js
  src/component/pages/InfoPage.js
  src/items/api/itemApi.js
  src/orders/api/ordersApi.js
  src/orders/views/OrderListPage.js
  src/review/api/reviewApi.js
  src/users/api/userApi.js
  src/users/api/userLoginApi.js
  src/users/components/OAuthRedirectHandler.js
  src/users/components/common/PasswordVaild.js
  src/users/utils/crypto.js
  src/users/utils/storage.js
Labels: ✨Feat, 🔮 이소현🔮

#138 💄 Style : Fix Footer padding, Boss delete
  public/index.html
  src/component/Footer.js
  src/users/api/userApi.js
  src/users/views/ModifyView.js
Labels: 🍸조민준🍸, 💄Style

#139 🐛 Fix : Encrypt fix
  src/cart/api/cartApi.js
  src/cart/views/PurchasePage.js
  src/component/Header.js
  src/component/pages/InfoPage.js
  src/items/api/itemApi.js
  src/items/views/ItemDetailView.js
  src/items/views/MypageItemCreateView.js
  src/orders/api/ordersApi.js
  src/orders/views/AdminOrdersListPage.js
  src/review/api/reviewApi.js
  src/users/api/userApi.js
  src/users/api/userLoginApi.js
  src/users/utils/storage.js
Labels: 🐛bug, 🔮 이소현🔮

#140 💄 Style : userroleinfo
  src/cart/views/PurchasePage.js
  src/component/Footer.js
  src/component/pages/InfoPage.js
  src/items/views/ItemDetailView.js
  src/items/views/MypageItemCreateView.js
  src/orders/views/AdminOrdersListPage.js
  src/users/components/common/UserRoleInfo.js
  src/users/components/css/UserRoleInfo.css
Labels: 🍸조민준🍸, 💄Style

#141 💄 Style : roleInfo css
  src/component/css/ModifyView.css
  src/component/pages/InfoPage.js
  src/users/components/css/AdminRoleInfo.css
  src/users/components/css/UserRoleInfo.css
Labels: 🔮 이소현🔮, 💄Style

#142 💄 Style : item create, edit page style
  src/items/components/css/CreateItem.css
  src/items/components/css/EditItem.css
  src/items/viewModels/useItemEditViewModel.js
  src/items/views/ItemCreateView.js
  src/items/views/ItemEditView.js
  src/orders/components/AdminOrderItem.js
  src/users/views/UserListView.js
Labels: 🐛bug, 🍸조민준🍸, 💄Style

#146 🐛 Fix : Oauth token fix
  src/users/components/OAuthRedirectHandler.js
Labels: 🐛bug

#147 🐛 Fix : Oauth fix
  src/users/components/OAuthRedirectHandler.js
Labels: 🐛bug, 🔮 이소현🔮

#149 💄 Style : ChatBot, Rolepage css
  src/chat/ChatbotView.css
  src/chat/ChatbotView.js
  src/users/components/common/AdminRoleInfo.js
  src/users/views/ModifyView.js
Labels: 🔮 이소현🔮
