Repository ToriArtis/2NY-Frontend, pull requests merged in 2024-08, with the labels that each got.

#109 ✨Feat: Init deploy setting
  .platform/hooks/prebuild/01_configure_swap_space.sh
  .platform/hooks/predeploy/01_serve_install.sh
  Procfile
  src/component/Header.js
  src/items/views/ItemListView.js
Labels: ✨Feat, 🍸조민준🍸

#110 ✨ Feat : Dashboard Add
  package-lock.json
  package.json
  src/component/Dashboard.js
  src/component/images/brand/brand-01.svg
  src/component/images/brand/brand-02.svg
  src/component/images/brand/brand-03.svg
  src/component/images/brand/brand-04.svg
  src/component/images/brand/brand-05.svg
  src/component/images/user/user-01.png
  src/component/images/user/user-02.png
  src/component/images/user/user-03.png
  src/component/images/user/user-04.png
  src/component/images/user/user-05.png
  src/component/images/user/user-06.png
  src/component/images/user/user-07.png
  src/component/images/user/user-08.png
  src/component/images/user/user-09.png
  src/component/images/user/user-10.png
  src/component/images/user/user-11.png
  src/component/images/user/user-12.png
  src/component/images/user/user-13.png
  src/component/pages/CardFour.js
  src/component/pages/CardOne.js
  src/component/pages/CardThree.js
  src/component/pages/CardTwo.js
  src/component/pages/ChartOne.js
  src/component/pages/ChartThree.js
  src/component/pages/ChartTwo.js
  src/component/pages/ChatCard.js
  src/component/pages/TableOne.js
  src/users/components/common/AdminRoleInfo.js
  src/users/views/LoginView.js
Labels: ✨Feat, 🔮 이소현🔮

#111 ✨Feat: : AdminPage ItemList
  src/items/components/css/MypageAllList.css
  src/items/views/MypageItemCreateView.js
Labels: 🔮 이소현🔮, 💄Style

#112 💄 Style : ItemList End
  src/items/components/css/MypageAllList.css
  src/items/viewModels/mypageItemListViewModel.js
  src/items/views/MypageItemCreateView.js
Labels: 🔮 이소현🔮, 💄Style

#113 💄 Style : DashBoard Css
  src/component/Dashboard.js
  src/component/pages/ChartOne.js
  src/component/pages/ChartThree.js
  src/component/pages/TableOne.js
  src/items/api/itemApiSimple.js
  src/items/components/css/MypageAllList.css
  src/items/views/MypageItemCreateView.js
  src/users/components/common/AdminRoleInfo.js
Labels: 🔮 이소현🔮, 💄Style

#114 ✨Feat: Refresh token rogic
  src/cart/api/cartApi.js
  src/items/api/itemApi.js
  src/orders/api/ordersApi.js
  src/review/api/reviewApi.js
  src/users/api/userApi.js
Labels: ✨Feat, 🍸조민준🍸

#115 ✨ Feat : User list page (user role setting)
  src/items/api/itemApi.js
  src/users/components/common/AdminRoleInfo.js
  src/users/views/UserListView.js
Labels: ✨Feat, 🍸조민준🍸

#117 ✨ Feat : Roleset page, item create page fix
  src/items/components/css/CreateItem.css
  src/items/views/ItemCreateView.js
  src/users/views/UserListView.js
Labels: ✨Feat, 🍸조민준🍸, 💄Style
